alpaca:
  key: "${ALPACA_KEY}"
  secret: "${ALPACA_SECRET}"
  base_url: "https://paper-api.alpaca.markets"
  data_url: "https://data.alpaca.markets"

mode: "backtest"

capital:
  initial_equity: 100000
  max_position_size: 0.05
  risk_per_trade: 0.01

strategies:
  enabled:
    - gap_fill
    - mean_reversion
    - momentum_breakout
    - opening_range_breakout
  performance_tracking:
    min_trades_for_evaluation: 10
    sharpe_kill_threshold: -0.5
    max_drawdown_kill_threshold: 0.15
    lookback_period_days: 30

schedule:
  timezone: "America/New_York"
  market_open: "09:30"
  market_close: "16:00"
  polling_interval: 30
  trading_windows:
    gap_fill: ["09:30", "11:00"]
    mean_reversion: ["10:00", "15:30"]
    momentum_breakout: ["09:45", "11:30"]
    opening_range_breakout: ["09:30", "10:15"]

logging:
  level: "INFO"
  file: "logs/trading.log"
  max_file_size: 10485760
  backup_count: 5

data:
  symbols: ["SPY", "QQQ", "IWM", "GLD", "TLT"]
  timeframes: ["1Min"]
  history_days: 30
