name: build-test-mutate

on: [push, pull_request]

jobs:
  java-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and unit tests
        run: ./mvnw -B clean test

      - name: Mutation-testing report
        run: ./mvnw -B org.pitest:pitest-maven:mutationCoverage

      - name: Upload PIT report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pit-html
          path: target/pit-reports

      - name: Shellcheck
        run: docker run --rm -v "$PWD":/mnt koalaman/shellcheck:stable $(git ls-files '*.sh')

