name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint shell scripts with shellcheck
        run: shellcheck scripts/*.sh ops/*.sh
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Build Java sources
        run: ./scripts/build.sh
      - name: Run Java tests (JUnit 5)
        run: |
          java -jar lib/junit-platform-console-standalone-1.10.2.jar \
            --class-path build/classes:build/test_classes:lib/* \
            --scan-class-path
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test_classes/
